%% Add annotations to itr
image_data = imread('/Users/barry/development/ovation-demo/brainslice_bw.jpg');
while(itr.hasNext())
    e = itr.next();
    r = e.getResponse('section-demo');
    if(isempty(r))
        imdata = NumericData(reshape(image_data,1,numel(image_data)),...
            size(image_data));
        r = e.insertResponse(e.getEpochGroup.getExperiment.externalDevice('section-demo','demo'),...
            struct2map(struct()),...
            imdata,...
            'intensity',...
            {'x','y'},...
            [1,1],...
            {'pixel','pixel'},...
            'public.jpeg');
    end
    r.addEllipseAnnotation('demo','my group',{'pixel','pixel'},[1,1],95,195,15,17);
end